services:
  - type: web
    name: goutham-portfolio-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm --prefix frontend run build
    startCommand: npm --prefix backend run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
